/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio3;

import javax.swing.JOptionPane;

/**
 *
 * @author adalberto
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */

double x[],y[],suma[],resta[];
public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdSuma = new javax.swing.JButton();
        cmdResta = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLongitud2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(51, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setBackground(new java.awt.Color(102, 102, 102));
        cmdCrear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdCrear.setForeground(new java.awt.Color(255, 255, 255));
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 20));

        cmdManual.setBackground(new java.awt.Color(102, 102, 102));
        cmdManual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdManual.setForeground(new java.awt.Color(255, 255, 255));
        cmdManual.setText("Llenado Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        cmdAutomatico.setBackground(new java.awt.Color(102, 102, 102));
        cmdAutomatico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdAutomatico.setForeground(new java.awt.Color(255, 255, 255));
        cmdAutomatico.setText("Llenado Automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, -1));

        cmdSuma.setBackground(new java.awt.Color(102, 102, 102));
        cmdSuma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdSuma.setForeground(new java.awt.Color(255, 255, 255));
        cmdSuma.setText("Suma");
        cmdSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, -1));

        cmdResta.setBackground(new java.awt.Color(102, 102, 102));
        cmdResta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdResta.setForeground(new java.awt.Color(255, 255, 255));
        cmdResta.setText("Resta");
        cmdResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, -1));

        cmdMostrar.setBackground(new java.awt.Color(102, 102, 102));
        cmdMostrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdMostrar.setForeground(new java.awt.Color(255, 255, 255));
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, -1));

        cmdBorrar.setBackground(new java.awt.Color(102, 102, 102));
        cmdBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdBorrar.setForeground(new java.awt.Color(255, 255, 255));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 440, 210));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("sumatoria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Iniciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Cantidad 1:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtLongitud1.setBackground(new java.awt.Color(255, 51, 0));
        txtLongitud1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLongitud1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitud1KeyTyped(evt);
            }
        });
        jPanel2.add(txtLongitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Longitud 2:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        txtLongitud2.setBackground(new java.awt.Color(255, 51, 0));
        txtLongitud2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLongitud2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitud2ActionPerformed(evt);
            }
        });
        txtLongitud2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitud2KeyTyped(evt);
            }
        });
        jPanel2.add(txtLongitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 240, 100));

        jPanel4.setBackground(new java.awt.Color(153, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(51, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(102, 102, 102));
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 110));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 240, 140));

        cmdSalir.setBackground(new java.awt.Color(255, 255, 204));
        cmdSalir.setFont(new java.awt.Font("Ravie", 2, 11)); // NOI18N
        cmdSalir.setForeground(new java.awt.Color(102, 102, 102));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtLongitud1.setText("");
        txtLongitud2.setText("");
        txtResultado.setText("");
        x=null;
        y=null;
        suma=null;
        resta=null;
        txtLongitud1.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        txtResultado.append("Los elementos del vector 1 son: ");
        for (int i = 0; i < x.length; i++) {
            txtResultado.append(x[i]+"\n");
        }
        txtResultado.append("Los elementos del vector 2 son: ");
        for (int i = 0; i < y.length; i++) {
            txtResultado.append(y[i]+"\n");
        }
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaActionPerformed
        int r;
        r = Integer.parseInt (txtLongitud1.getText ().trim());
        resta = new double [r];

        for (int i = 0; i < x.length; i++) {
            resta[i]=(x[i]-y[i]);
        }
        for (int i = 0; i < resta.length; i++) {
            txtResultado.append("El resultado de la resta en la posición "+i+" es: "+resta[i]+"\n");

        }
    }//GEN-LAST:event_cmdRestaActionPerformed

    private void cmdSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumaActionPerformed
        int s;

        s = Integer.parseInt (txtLongitud1.getText ().trim());
        suma = new double [s];
        for (int i = 0; i < x.length; i++) {
            suma[i]=(x[i]+y[i]);
        }
        for (int i = 0; i < suma.length; i++) {
            txtResultado.append("El resultado de la suma en la posición "+i+" es: "+suma[i]+"\n");

        }
    }//GEN-LAST:event_cmdSumaActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
        double num,n1,n2;

        num=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el número hasta donde quiere el llenado: "));
        while(num<x.length){
            JOptionPane.showMessageDialog(this, "Digite un número mayor a: "+x.length);
            num=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el número hasta donde quiere el llenado: "));
        }
        for (int i = 0; i < x.length; i++) {
            n1=(int)(Math.random()*num+1);
            x[i]=n1;
        }
        while(num<y.length){
            JOptionPane.showMessageDialog(this, "Digite un número mayor a: "+y.length);
            num=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el número hasta donde quiere el llenado: "));
        }
        for (int i = 0; i < y.length; i++) {
            n2=(int)(Math.random()*num+1);
            y[i]=n2;
        }
        JOptionPane.showMessageDialog(this, "Vectores Llenados Correctamente");
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        double n1,n2;
        for (int i = 0; i < x.length; i++) {
            n1=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el elemento del vector 1 en la posición: "+i));
            x[i]=n1;
        }
        for (int i = 0; i < y.length; i++) {
            n2=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el elemento del vector 2 en la posición "+i));
            y[i]=n2;
    }    
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int long1,long2;
        if(txtLongitud1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la cantidad  1.","ERROR",JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();
        }else if(txtLongitud2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la cantidad 2.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLongitud2.requestFocusInWindow();
        }else if(Integer.parseInt(txtLongitud1.getText().trim())==0){
            JOptionPane.showMessageDialog(this, "La cantidad no puede ser cero.","ERROR",JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();
            txtLongitud1.selectAll();
        }else if(Integer.parseInt(txtLongitud2.getText().trim())==0){
            JOptionPane.showMessageDialog(this, "La cantidad no puede ser cero.","ERROR",JOptionPane.ERROR_MESSAGE);
            txtLongitud2.requestFocusInWindow();
            txtLongitud2.selectAll();
        }else{
            long1=Integer.parseInt(txtLongitud1.getText());
            long2=Integer.parseInt(txtLongitud2.getText());
            x = new double[long1];
            y = new double[long2];
            JOptionPane.showMessageDialog(this, "Los vectores Se Crearon Exitosamente");
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void txtLongitud1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitud1KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtLongitud1KeyTyped

    private void txtLongitud2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitud2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitud2ActionPerformed

    private void txtLongitud2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitud2KeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtLongitud2KeyTyped

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdResta;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton cmdSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLongitud1;
    private javax.swing.JTextField txtLongitud2;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
